"use client";

import type { CardOrigin } from "@/lib/types";

/**
 * Where a card came from, said on the card itself.
 *
 * Two signals, deliberately, because one cannot carry both facts. The violet
 * AI mark means "a model wrote this" — true of every card in the app, so it
 * can never distinguish one kind from the other. The second, uncoloured mark
 * carries the part that actually varies: whether there is any uploaded source
 * standing behind it.
 *
 * Colour stays honest under the design system's rule that each hue means
 * exactly one thing: violet is "model-authored", and "no source" gets no hue
 * at all rather than borrowing a warning colour it has not earned. A
 * knowledge card is not an error — it is a card with a weaker warranty, and
 * the student is the one who decides what to do about that.
 */
const NO_SOURCE_TITLE =
  "Written from the model's own knowledge of the syllabus unit. No uploaded " +
  "source stands behind it — check it before you trust it.";

export function Provenance({
  origin,
  /** "chip" matches the review screen's `.prov` pills; "inline" matches the
   *  denser metadata row on the approve queue. Same meaning either way. */
  variant = "inline",
}: {
  origin?: CardOrigin;
  variant?: "inline" | "chip";
}) {
  if (variant === "chip") {
    return (
      <>
        <span className="prov prov--ai">AI</span>
        {origin === "knowledge" && (
          <span className="prov" title={NO_SOURCE_TITLE}>
            no source
          </span>
        )}
      </>
    );
  }
  return (
    <>
      <span
        className="text-ai text-[10px] font-medium tracking-[0.08em] leading-none"
        style={{ fontFamily: "var(--font-mono)" }}
        title="Generated by the model"
      >
        AI
      </span>
      {origin === "knowledge" && (
        <span
          className="text-[10px] font-medium tracking-[0.08em] leading-none
            text-fg-3 border border-line rounded-xs px-1 py-px"
          style={{ fontFamily: "var(--font-mono)" }}
          title={NO_SOURCE_TITLE}
        >
          NO SOURCE
        </span>
      )}
    </>
  );
}
